### ISSUE TITLE
Hard coded "SIAL_20161020"

### ISSUE THREAD

**Issue by ellisp** [nz-social-investment-agency/social_housing#3]
Line 33 of https://github.com/nz-social-investment-agency/social_housing/blob/master/sasprogs/sh_align_sialevents.sas has a hard coded reference to one of your versions of the SIAL, which won't work for other users.

Also, this would be easier to spot if you had stuck to your [style guide limit](https://github.com/nz-social-investment-agency/social_housing/blob/master/sasprogs/sh_align_sialevents.sas) of 130 characters :)

**Comment by vinaybenny** [comment]
Thanks Peter.

Root cause: The SIAL reference is put there because of ACC refresh issues in the IDI refresh version 20170420, which led to no data availability in ACC tables before 2014. This required us to create an ad-hoc SIAL table which points to the previous IDI refresh for ACC data. This reference can be removed now as the latest IDI refresh has fixed the ACC data availabilty issues.

Fix: Edited the SIAL table reference to point back to the original SIAL table. Lines limited to 130 character limit. To be closed once code is signed out.
